const godotExportHelpers = typeof module !== 'undefined' ? require('./exportCommon') :
    { createDemoApplePng, cleanDialogueProject, validateDialogueProject, createExportZip, downloadDialogueBlob };

function buildGodotProject(source, template) {
    const data = godotExportHelpers.cleanDialogueProject(source);
    const plainJson = JSON.stringify(data);
    for (const character of data.characters || []) {
        character.dialogueNodes = character.dialogueNodes || [];
        character.outgoingLines = character.outgoingLines || [];
        for (const node of character.dialogueNodes) node.outgoingLines = node.outgoingLines || [];
    }
    godotExportHelpers.validateDialogueProject(data);
    const files = { ...template };
    files['art/apple.png'] = godotExportHelpers.createDemoApplePng();
    files['dialogue.json'] = plainJson;
    const height = Math.max(640, 260 + Math.ceil(data.characters.length / 4) * 150);
    let scene = `[gd_scene load_steps=5 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1"]
[ext_resource type="PackedScene" path="res://scenes/player.tscn" id="2"]
[ext_resource type="PackedScene" path="res://scenes/npc.tscn" id="3"]
[ext_resource type="PackedScene" path="res://scenes/dialogue_ui.tscn" id="4"]

[node name="DialoguePlayground" type="Node2D"]
script = ExtResource("1")

[node name="Player" parent="." instance=ExtResource("2")]
position = Vector2(140, 140)
world_size = Vector2(960, ${height})

[node name="NPCs" type="Node2D" parent="."]
`;
    data.characters.forEach((character, index) => {
        const x = 140 + (index % 4) * 220;
        const y = 280 + Math.floor(index / 4) * 150;
        const hex = /^#[0-9a-f]{6}$/i.test(character.bgColor) ? character.bgColor : '#b68af7';
        const color = [1, 3, 5].map(start => Math.max(0.35, parseInt(hex.slice(start, start + 2), 16) / 255).toFixed(4));
        scene += `
[node name="NPC_${index + 1}" parent="NPCs" instance=ExtResource("3")]
position = Vector2(${x}, ${y})
character_index = ${index}
character_id = ${JSON.stringify(String(character.characterID))}
tint = Color(${color.join(', ')}, 1)
`;
    });
    scene += '\n[node name="DialogueUI" parent="." instance=ExtResource("4")]\n';
    files['scenes/main.tscn'] = scene;
    let project = `; Generated by Game Dialogue Maker. Open with Godot 4.5+.
config_version=5

[application]
config/name="Dialogue Playground"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.5", "GL Compatibility")

[display]
window/size/viewport_width=960
window/size/viewport_height=640
window/size/window_width_override=960
window/size/window_height_override=640
window/stretch/mode="canvas_items"

[rendering]
renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
environment/defaults/default_clear_color=Color(0.07, 0.09, 0.14, 1)

[input]
`;
    const bindings = { move_left: [65, 4194319], move_right: [68, 4194321], move_up: [87, 4194320], move_down: [83, 4194322] };
    for (const [action, codes] of Object.entries(bindings)) {
        project += `\n${action}={\n"deadzone": 0.2,\n"events": [${codes.map(code => `Object(InputEventKey,"physical_keycode":${code})`).join(', ')}]\n}\n`;
    }
    files['project.godot'] = project;
    files['.gitignore'] = '.godot/\n';
    return files;
}

function exportGodot() {
    const files = buildGodotProject(gameDialogueMakerProject, godotTemplate);
    godotExportHelpers.downloadDialogueBlob(godotExportHelpers.createExportZip(files), 'dialogue-godot.zip');
}

if (typeof module !== 'undefined') module.exports = { buildGodotProject };
